### ISSUE TITLE
SQLiteQuery Exception after setup - Build Alpha 1.0 - April 21 16:31

### ISSUE THREAD

**Issue by rawmain** [DP-3T/dp3t-app-android#24]
Hello

Checking latest build package Alpha 1.0 (1) - April 21 16:31 .

On all my test-devices (from API Level 23 to 29) there is just an initial SQLiteQuery Exception after setup = app crashes. 

Then, after relaunching the app (without rebooting the devices), it manages to open DB OK & everything works fine = ok foreground & background scan & notification management.

This is the related Error logcat for such initial exception :

---------------------------------
```
04-21 21:28:32.810 24819 24844 E bt_btif : register application first_unuse rcb_idx = 0
04-21 21:28:32.879 24819 24844 E bt_btif : create service rcb_idx = 0
04-21 21:28:35.327 25362 25460 E SQLiteLog: (14) cannot open file at line 29011 of [2ef4f3a5b1]
04-21 21:28:35.327 25362 25460 E SQLiteLog: (14) os_unix.c:29011: (24) open(/data/user/0/org.dpppt.android.app/databases) -
04-21 21:28:35.330 25362 25460 E SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
04-21 21:28:35.330 25362 25460 E SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/org.dpppt.android.app/databases/dp3t_sdk.db-journal) -
04-21 21:28:35.330 25362 25460 E SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
04-21 21:28:35.330 25362 25460 E SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/org.dpppt.android.app/databases/dp3t_sdk.db-journal) -
04-21 21:28:35.330 25362 25460 E SQLiteLog: (14) statement aborts at 14: [SELECT id, date, ephid, associated_known_case FROM contacts WHERE date=? ORDER BY id] unable to open database file
04-21 21:28:35.330 25362 25460 E SQLiteQuery: exception: unable to open database file (code 14); query: SELECT id, date, ephid, associated_known_case FROM contacts WHERE date=? ORDER BY id
04-21 21:28:35.331 25362 25394 E Parcel  : dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
04-21 21:28:35.333 25362 25460 E AndroidRuntime: FATAL EXCEPTION: DatabaseThread
04-21 21:28:35.333 25362 25460 E AndroidRuntime: Process: org.dpppt.android.app, PID: 25362
04-21 21:28:35.333 25362 25460 E AndroidRuntime: Theme: themes:{default=, iconPack:system}
04-21 21:28:35.333 25362 25460 E AndroidRuntime: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.Database.getContactsFromCursor(Database.java:164)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.Database.getContacts(Database.java:159)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.Database.lambda$null$0$Database(Database.java:55)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.-$$Lambda$Database$hqP5Ka9ktLFtK2AP_0mwko0IAlE.getContacts(lambda)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.crypto.CryptoModule.checkContacts(CryptoModule.java:197)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.Database.lambda$addKnownCase$2$Database(Database.java:55)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at org.dpppt.android.sdk.internal.database.-$$Lambda$Database$OL9TXV4XAz0TiMW-AA75yNh6wuw.run(lambda)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
04-21 21:28:35.333 25362 25460 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
```
---------------------------------`

Since there wasn't such issue with build Alpha 1.0 - April 17 01:06, I'm checking subsequent commits (debug related).

By the rest, positive ID match is working OK as in initial Alpha builds.

![IMG_20200421_210747](https://user-images.githubusercontent.com/18743336/79914413-8ba93500-8425-11ea-8bb1-4e3a37ed20b4.jpg)
![IMG_20200421_210825](https://user-images.githubusercontent.com/18743336/79914415-8cda6200-8425-11ea-9155-1f6dc7a5ce8d.jpg)
![IMG_20200421_212217](https://user-images.githubusercontent.com/18743336/79914416-8cda6200-8425-11ea-8c2a-bd3bbb7f6798.jpg)

**Comment by simonroesch** [comment]
This is actually and issue of the https://github.com/DP-3T/dp3t-sdk-android and has been fixed in the SDK. The new sdk version will be included in the demo app soon!
